const langs = {
  "ru": {
    "taskssolve": "Какие задачи решает",
    "howitworks": "Как это работает",
    "sermkarma": "Serm Karma",
    "price": "Стоимость",
    "contacts": "Контакты",
    "submitrequest": "Оставь заявку",
    "onlinereputation": "Система управления репутацией в интернете",
    "negativereviews": "Система купирования негативных отзывов",
    "helpstosolve": "Задачи, которые система помогает решить:",
    "implementation": "Внедрение",
    "implementationsystem": "системы контроля и мотивации сотрудников первой линии позволит улучшить качество их работы, увеличит количество естественных положительных отзывов в картографических сервисах и на других популярных сайтах-отзовиках.",
    "analyticsandmonitoring": "Удобная аналитика и мониторинг отзывов в интернете",
    "employeepersonalpage": "Для каждого сотрудника первой линии шоу-рума создается персонализированная ссылка с данными о сотруднике и его отделе, которой он сможет делиться через точки касания:",
    "qrattheworkplace": "Размещение QR-кода на рабочем месте",
    "messagingviamessengerorsms": "Сообщение в мессенджере или смс",
    "electronicemployeeidcard": "Электронный бейдж",
    "printeddocuments": "Печатная форма первичной документации (заказ наряд или договор купли продажи)",
    "usingthispagetorate": "С помощью этой ссылки клиенты смогут оценить работу сотрудника.",
    "suggestedtowritetheirfeedback": "Для клиентов, которые поставили низкую оценку с 1 до 3 выходит окно, в котором они могут написать, что именно не устроило. Это позволяет оперативно решить проблему и купирует дальнейшее распространение негатива.",
    "canleaveapositivereview": "Клиентам, поставившим оценки от 4 до 5 предлагается перейти на картографические сервисы, где клиент, в случае регистрации на них, может оставить положительный отзыв и оценку. Мы рекомендуем внедрить KPI в систему мотивации для сотрудников первой линии: 50% клиентов должны поставить оценку в картографических сервисах.",
    "aftertheclientleavesarating": "После того, как клиент ставит оценку, данные отправляются в группу Telegram с ответственными сотрудниками или на их E-mail",
    "allthestatisticsforeachemployee": "Также вся статистика по каждому сотруднику с его оцен��ой автоматически собирается в таблице Google Docs.",
    "minimumpackage": "Минимальный пакет",
    "optimalpackage": "Оптимальный пакет",
    "maximumpackage": "Максимальный пакет",
    "enterprisepackage": "Корпоративный пакет",
    "creationofpersonalpagesforeachemployee": "Создание персональных страниц для каждого сотрудника",
    "personalpagesonclientsdomain": "Размещение персональных страниц на домене клиента",
    "productionofpersonalidcards": "Производство персональных бейджей",
    "negativereviewsfiltering": "Фильтрация негативных отзывов",
    "developmentofmaterialsfortouchpoints": "Разработка материалов для точек контакта",
    "integrationwithtelegramemail": "Интеграция с Telegram и/или электронной почтой",
    "reportgenerationforeachemployee": "Формирование отчётов по каждому сотруднику",
    "integrationwithmapserviceseviewsites": "Интеграция с картографическими сервисами и/или сайтами отзовиками",
    "reportgenerationforeachlocation": "Формирование отчётов по точке (за один адрес на картографическом сервисе)",
    "personalreviewmanager": "Персональный менеджер по работе с отзывами",
    "countbadges": "Количество бейджей в пакете",
    "priceforoneidcard": "Цена за один бейдж",
    "packagecost": "Стоимость пакета",
    "ourcontacts": "Наши контакты",
    "callus": "Позвоните нам",
    "weareintelegram": "Мы в Телеграм",
    "evaluatetheservice": "Оцените сервис",
    "feedback": "Расскажите нам, что вам непонятно или что нужно добавить в наш проект, чтобы получить Ваше ❤️!",
    "comment": "Ваш комментарий *",
    "personaldata": "Я согласен на обработку персональных данных",
    "thanksforrating": "Спасибо за оценку!",
    "letstalk": "Давайте поговорим, как мы можем внедрить нашу систему в Ваш бизнес процесс. Оставьте контакт и укажите время когда удобно с Вами связаться.",
    "yourphone": "Ваш телефон",
    "besttime": "Удобное время для звонка:",
    "send": "Отправить",
    "sendbtnaction": "Отправляем...",
    "oops": "Упс!",
    "errortext": "Что-то пошло не так. Перезагрузите страницу и попробуйте снова.",
    "commenterror": "Поле обязательно для заполнения и минимальное количество символов -",
    "phoneerror": "Телефон является обязательным полем",
    "incorrectphoneerror": "Введен некорректный номер телефона",
    "agreeerror": "Чтобы продолжить, установите флажок",
    "thanksforcomment": "Спасибо за Ваш комментарий!",
    "thanksforcommenttext": "Для нас очень важно Ваше мнение!",
    "thanksforratingtext": "В скором времени мы свяжемся с Вами!",
    "mincountbadges": "-",
    "optcountbadges": "5 шт/мес",
    "maxcountbadges": "10 шт/мес",
    "enterprisecountbadges": "По запросу",
    "minpriceforonecard": "2 000 ₽",
    "optpriceforonecard": "0 ₽",
    "maxpriceforonecard": "0 ₽",
    "optpackageprice": "5 000 ₽/мес",
    "maxpackageprice": "10 000 ₽/мес",
    "enterpriseprice": "По запросу"
  },
  "en": {
    "taskssolve": "What tasks does it solve",
    "howitworks": "How it works",
    "sermkarma": "Serm Karma",
    "price": "Price",
    "contacts": "Contacts",
    "submitrequest": "Submit a request",
    "onlinereputation": "Online reputation management system",
    "negativereviews": "Negative reviews suppression system",
    "helpstosolve": "Tasks that the system helps to solve:",
    "implementation": "The implementation",
    "implementationsystem": "of control and motivation system for frontline employees will improve the quality of their work and increase the number of natural positive reviews on mapping services and other popular review websites.",
    "analyticsandmonitoring": "Convenient analytics and online reviews monitoring",
    "employeepersonalpage": "For each frontline employee a personal page is created. It contains contact information, photo. This information can be downloaded and saved as new contact in smatphone right from this page. Link to this page can be shared through different touchpoints:",
    "qrattheworkplace": "Placement of the QR code at the workplace",
    "messagingviamessengerorsms": "Messaging via messenger or SMS",
    "electronicemployeeidcard": "Electronic employee ID card",
    "printeddocuments": "Printed primary accounting documents (purchse order or sales contract)",
    "usingthispagetorate": "Using this page, customers will be able to rate the employee's performance.",
    "suggestedtowritetheirfeedback": "For customers who have given a low rating from 1 to 3, it is suggested to write their feedback in a form on site. This allows you to quickly resolve the issue and deal with bad reviews before they are posted somewhere else.",
    "canleaveapositivereview": "Customers who rate from 4 to 5 are offered to visit mapping services, where they can leave a positive review and rating. We recommend implementing KPIs in the motivation system for frontline employees depending on reviews left.",
    "aftertheclientleavesarating": "After the client leaves a rating, the data is sent to responsible employees by Telegram or email.",
    "allthestatisticsforeachemployee": "Also, all the statistics for each employee, along with their ratings, are automatically collected in a Google Spreadsheet.",
    "minimumpackage": "Minimum package",
    "optimalpackage": "Optimal package",
    "maximumpackage": "Maximum package",
    "enterprisepackage": "Enterprise package",
    "creationofpersonalpagesforeachemployee": "Creation of personal pages for each employee",
    "personalpagesonclientsdomain": "Personal pages on the client's domain",
    "productionofpersonalidcards": "Production of personal ID cards",
    "negativereviewsfiltering": "Negative reviews filtering",
    "developmentofmaterialsfortouchpoints": "Development of materials for touchpoints",
    "integrationwithtelegramemail": "Integration with Telegram and/or email",
    "reportgenerationforeachemployee": "Report generation for each employee",
    "integrationwithmapserviceseviewsites": "Integration with map services and/or review sites",
    "reportgenerationforeachlocation": "Report generation for each location (for one address on mapping service)",
    "personalreviewmanager": "Personal review manager",
    "countbadges": "Count of badges in the package",
    "priceforoneidcard": "Price for one ID Card",
    "packagecost": "Package cost",
    "ourcontacts": "Our contacts",
    "callus": "Call us",
    "weareintelegram": "We are in Telegram",
    "evaluatetheservice": "Evaluate the service",
    "feedback": "Please tell us what is missing or disappointing in your experience with us or if there is anything that needs to be added to our project to earn your ❤️!",
    "comment": "Your comment *",
    "personaldata": "I agree to the processing of personal data",
    "thanksforrating": "Thanks for your rating!",
    "letstalk": "Let's talk about how we can introduce our system into your business process. Leave contact and specify the time when it is convenient to contact you.",
    "yourphone": "Your phone number",
    "besttime": "Convenient time for calling:",
    "send": "Send",
    "sendbtnaction": "Sending...",
    "oops": "Oops!",
    "errortext": "Something went wrong. Reload the page and try again.",
    "commenterror": "The field is required and the minimum number of characters is",
    "phoneerror": "Phone is a required field",
    "incorrectphoneerror": "Invalid phone number entered",
    "agreeerror": "To continue, check the box",
    "thanksforcomment": "Thank you for your comment!",
    "thanksforcommenttext": "Your opinion is very important for us!",
    "thanksforratingtext": "We will contact you shortly!",
    "mincountbadges": "-",
    "optcountbadges": "5 pc/month",
    "maxcountbadges": "10 pc/month",
    "enterprisecountbadges": "Custom",
    "minpriceforonecard": "$20",
    "optpriceforonecard": "$0",
    "maxpriceforonecard": "$0",
    "optpackageprice": "$50/month",
    "maxpackageprice": "$100/month",
    "enterpriseprice": "Custom"
  }
};
export default langs;